[technote]
id = "RTN-067"
series_id = "RTN"
canonical_url = "https://rtn-067.lsst.io"
github_url = "https://github.com/lsst/rtn-067"
github_default_branch = "main"
date_created = "2023-10-30T23:59:28Z"

[[technote.authors]]
name = { name = "Frossie Economou" }
# orcid = "https://orcid.org/..."
# affiliations = [
#     { name = "Rubin Observatory", ror = "https://ror.org/048g3cy84" }
# ]

[technote.status]
state = "draft"
